language: php

php:
  - 5.6
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --dev --prefer-source

script:
  - phpunit --configuration tests/phpunit.xml
